#!/bin/sh

cd ~/.vim_runtime
#  init environ string
environ=''
repo_url="https://github.com/junegunn/fzf.git"
repo_dir="~/.fzf"
#  install addons
# if current os is macos
if [[ "$(uname)" == "Darwin" ]]; then
  echo "installing addons for macos"
  # add fzf
  brew install fzf
  environ+="set rtp+=/usr/local/opt/fzf"
  brew install the_silver_searcher
  brew install ripgrep
  brew install ack

else
  echo "installing addons for linux"
  # add fzf
  if [ ! -d "$repo_dir" ]; then
    # 克隆仓库
    git clone "$repo_url" "$repo_dir"
    echo "仓库克隆成功！"
  else
      echo "仓库目录已存在，跳过克隆操作。"
  fi
  ~/.fzf/install
  echo "fzf installed"
    # rmdir "$DIRECTORY"
  environ+="set rtp+=~/.fzf"
  curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  sudo dpkg -i ripgrep_13.0.0_amd64.deb
  sudo apt-get install silversearcher-ag

fi
echo $environ

echo '
" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim
set runtimepath+=~/.vim_runtime
'"$environ"'
source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
